# Generated by Django 2.1.5 on 2019-03-26 18:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 27, 1, 57, 13, 295618), verbose_name='date published'),
        ),
    ]
